domains
	dish,stat,typeoftaste=symbol
predicates
	taste(dish,typeoftaste)
	state(dish,stat)
clauses
	taste("Paniyaram","sweet").
	taste("Dhokla","sweet-sour").
	taste("Vada-pav","spicy").
	taste("Kada halwa","sweet").
	taste("Litti Chokha","sweet").
	
	
	state("Paniyaram","Kerela").
	state("Dhokla","gujarat").
	state("Vada-pav","Maharashtra").
	state("Kada halwa","Punjab").
	state("Litti Chokha","Bihar").
